name: Python CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted  # You can change this to 'windows-latest' if you need a Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt file in your repo

      - name: Run tests
        run: |
          python -m unittest snake_game.py # Adjust the path to your test directory if needed